### PR TITLE
Fail test if reporter output differs

### PR DESCRIPTION
**Pull request by krlmlr**
Tests status of tests/testthat/reporters directory using git2r.

### CODE REVIEW

**Comment by krlmlr** [comment]
Will rework to use plain text file comparison.

**Comment by hadley** [comment]
How about a generic `expect_no_git_changes()` or similar?  

I also wondered if we wanted something specialised for regression testing - i.e. a variant of `test_that()`

**Comment by krlmlr** [comment]
This PR is currently broken -- I don't understand why file.copy() isn't invoked.

How about `expect_output(..., file = "reporters/...txt")`, which would collect output and write it to the file (if it is different)? I'm not too convinced about integrating this with Git anymore -- these tests should run on CRAN (and for an installed package) as well.

**Comment by hadley** [comment]
Also they should definitely be saved and checked into git as this makes it easy for me to visually inspect changes and verify whether or not they're ok.  This is more like a regression test, so I don't think it should fail automatically if different to previous.

**Comment by krlmlr** [comment]
Agreed. But what if a third party changes the code but forgets to update the "golden" files? Failing the test gives you an early clue. If the files are updated in-place, the tests fail only once.

**Comment by hadley** [comment]
That doesn't seem likely in this scenario, because I'd notice in the pull request. I really don't want automation to make this more fragile for me.

**Comment by krlmlr** [comment]
You notice in the PR only if the contributor updates the "golden" files. Failing the test in case of a difference errs on the safe side and has only a minor impact for your work on the code (because files are still updated in-place). That said, feel free to close this if you don't like it.

**Comment by hadley** [comment]
I'd rather think it through in general in the future. The current code suits me well for now

**Pull request closed without merging**
