### PR TITLE
Add skip_on_bioc

### PR DESCRIPTION
**Pull request by thomasp85**
The inspected environment variable is recommended by Dan Tenenbaum who is responsible for the Bioconductor build machines

### CODE REVIEW

**Comment by thomasp85** [comment]
I've not added any unit tests (ironically) as this doesn't seem to be done for the skip functions

**Comment by thomasp85** [comment]
Ahh - I was blindly copying `skip_on_appveyor()`, which seems to forego this convention...

**Comment by hadley** [comment]
Could you please also add a bullet to NEWS?

**Comment by thomasp85** [comment]
Sure thing

**Comment by hadley** [comment]
Thanks!

**Pull request closed without merging**
