### PR TITLE
Don't allow base packages to be mocked

### LINKED ISSUE #546: Prevent with_mock from touching base R packages
As it breaks things with the byte code compiler (and it's just a bad idea in general)

### PR DESCRIPTION
**Pull request by hadley**
Fixes #546

@krlmlr I'm going to need your help to figure out how to modify the tests that rely on mocking base packages.

### CODE REVIEW

**Comment by krlmlr** [comment]
I'll take a look and update the branch.

**Comment by hadley** [comment]
@krlmlr could you please take a look again?

**Comment by krlmlr** [comment]
I think we decided that we just can't mock base packages. I'll remove/update these tests, but I also need to refactor package code. When would be a good time to do this, to avoid conflicts?

**Comment by krlmlr** [comment]
Turned out it's just a few places.

**Comment by krlmlr** [comment]
Why can't I request a review from you on this PR?

**Comment by hadley** [comment]
I think it's because it's my PR originally?

**Comment by krlmlr** [comment]
Yes, of course. Added NEWS.

**Pull request merged**
