### PR TITLE
Report bare expectations

### LINKED ISSUE #427: expectations not wrapped in 'test_that()' call don't get reported
Not sure if this is intended or not, but I noticed that with the current development version of `testthat` tests are not reported (e.g. with the little `.`) when not wrapped in `test_that()`.

Is this a regression or intended behavior?

---

Repro:

``` sh
cd $TMPDIR
rm -rf hellotestthat
R -e 'devtools::create("hellotestthat")'
cd hellotestthat
R -e 'devtools::use_testthat()'
echo -e 'context("Hello")\nexpect_true(TRUE)\n' > tests/testthat/test-hello.R
R -e 'devtools::test()'
```

With old testthat:

```
> devtools::test()
Loading hellotestthat
Loading required package: testthat
Testing hello
Hello : .

DONE
```

New testthat:

```
> devtools::test()
Loading hellotestthat
Loading required package: testthat
Testing hello
Hello:

DONE ===========================================================================
```

### PR DESCRIPTION
**Pull request by krlmlr**
This makes sure that all testing code is run in a reporter and with the usual testthat condition handling. Fixes #427.

CC @kevinushey.

### CODE REVIEW

**Comment by kevinushey** [comment]
Nice!

I wonder if the `wrap` argument is really needed? It'd be nice (IMO) if that could be the default behavior, but I'm assuming you backed it out because of failing tests / other complications?

**Comment by krlmlr** [comment]
We must not wrap the helpers, but perhaps we can make wrap = TRUE the default.

**Comment by krlmlr** [comment]
Second take, now with wrap = TRUE by default and all tests passing.

**Comment by kevinushey** [comment]
:tada:

**Comment by hadley** [comment]
LGTM. Could you please merge/rebase?

**Comment by krlmlr** [comment]
Using Markdown now.

**Comment by hadley** [comment]
Is this good to merge?

**Comment by krlmlr** [comment]
I think so.

**Pull request merged**
