### PR TITLE
throws_error(NA) has unexpected behavior

### PR DESCRIPTION
**Pull request by krlmlr**
- with regexp=NA and an actual error thrown
- failure message with successful code and expected error

Also affects expect_error(..., NA).

Solved by adapting implementation to that of gives_warning().

### CODE REVIEW

**Comment by hadley** [comment]
Looks good. Can you add a bullet to NEWS please?

**Comment by krlmlr** [comment]
Done.

**Comment by krlmlr** [comment]
Moved bullet up.

**Comment by famuvie** [comment]
Neat solution, indeed!

**Comment by krlmlr** [comment]
Merged with master.

**Pull request merged**
