### PR TITLE
fix for solaris

### PR DESCRIPTION
**Pull request by jeroenooms**

### CODE REVIEW

**Comment by hadley** [comment]
Thanks - can you confirm that once this is in place the unit tests pass on Solaris?

**Comment by jeroenooms** [comment]
Yes it now passes check on both sparc and x86.

**Comment by jeroenooms** [comment]
We can only guess what timezone value BDR is going to get on his box though... maybe you want to ignore the timezone attribute alltogether?

**Comment by hadley** [comment]
I wish I could, but I think it's important.  Let me resubmit again, with an explanatory note.

**Pull request merged**
