### PR TITLE
Support shorthand syntax reporter1+reporter2+...

### PR DESCRIPTION
**Pull request by krlmlr**
for creating a multi-reporter that reports to reporter1, reporter2 and the others.

Now `find_reporter("")` throws an error.

Use case: `devtools::test(reporter = "summary+stop")` in a Makefile.

@hadley: I'm not sure which of the two below is the better syntax:

```
devtools::test(reporter = "summary+stop")
devtools::test(reporter = c("summary", "stop"))
```

I could also support both. I still need to add documentation and NEWS, please let me know what you think before I proceed.

### CODE REVIEW

**Comment by hadley** [comment]
I'd prefer a character vector.

**Comment by krlmlr** [comment]
Now supporting both character vector and "+" notation.

**Comment by hadley** [comment]
Unless you have a strong preference, I'd prefer to just have the character vector version.

**Comment by krlmlr** [comment]
Removed support for "+" notation.

**Comment by hadley** [comment]
LGTM - feel free to news it & merge.

**Pull request merged**
