### PR TITLE
avoid use of now-removed 'copy()' method

### PR DESCRIPTION
**Pull request by kevinushey**
Fixes https://github.com/hadley/testthat/issues/405.

### CODE REVIEW

**Comment by hadley** [comment]
Are you sure that's sufficient? I was thinking an R6 clone would be needed

**Comment by kevinushey** [comment]
It looks like `find_reporter()` will just construct a new reporter when the argument is a string, but I think you're right that explicitly calling `find_reporter()` first and then cloning is the way to go.

**Comment by kevinushey** [comment]
Alright, now done using R6 clone rather than copy.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
