### PR TITLE
changed the testthat_results data frame column "skipped" from numeric…

### PR DESCRIPTION
**Pull request by kforner**
… to logical

### CODE REVIEW

**Comment by hadley** [comment]
Why? Couldn't there be multiple skipped tests?

**Comment by kforner** [comment]
unless mistaken, there's a row per test, and a test can only be skipped once.

**Comment by kforner** [comment]
Why do you mean by "multiple skipped tests" ? I thought that a skip() call ended the current test execution, like a return().

**Comment by kforner** [comment]
seems like the travis check failed because of the coverage. The R CMD check was successful...

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
