### PR TITLE
Summary of skipped tests

### LINKED ISSUE #234: Feature request: TODO tests
In Perl's TAP testing framework, the developer can mark certain tests as "TODO", which are useful when you know what the correct result should be, but the code doesn't produce it yet:

    http://testanything.org/tap-specification.html

Could this be added to the various `expect_*` and `is_*` functions, perhaps as an extra `todo` argument, or maybe as a `style=c('test','todo','skip')` argument that allows different options (to prevent future arg proliferation)?

### PR DESCRIPTION
**Pull request by krlmlr**
Shows skipped tests, but only if there are no failures. Example:

```
Testing bigrquery
DBItest: Connection : ..SS..S.SS
1. Skip: DBItest: cannot_query_disconnected --------------------------------------------------------------------------------------------------------------
Not yet implemented

2. Skip: DBItest: cannot_disconnect_twice ----------------------------------------------------------------------------------------------------------------
by request

3. Skip: DBItest: stress_connections ---------------------------------------------------------------------------------------------------------------------
by request

4. Skip: DBItest: get_info_connection --------------------------------------------------------------------------------------------------------------------
Not yet implemented

5. Skip: DBItest: stress_load_connect_unload -------------------------------------------------------------------------------------------------------------
by request

DONE 
```

Will improve the coding once we agree on the concept.

Fixes #234.

CC @HarlanH @kenahoo-windlogics

Fixes #349 (=includes it).

### CODE REVIEW

**Comment by hadley** [comment]
I like the idea, but I think the output could be more compact, e.g.:

```
Skip: 
  
1. DBItest: cannot_query_disconnected - Not yet implemented
2. DBItest: cannot_disconnect_twice - by request
3. DBItest: stress_connections - by request
4. DBItest: get_info_connection - Not yet implemented
5. DBItest: stress_load_connect_unload - by request
```

**Comment by hadley** [comment]
This might also be a good template for how to handle warnings (#310)

**Comment by krlmlr** [comment]
Implemented more compact output.

**Comment by krlmlr** [comment]
Related: #310.

**Comment by krlmlr** [comment]
@hadley: How to include the context in the output, if at all? (Same question for error and warning output.)

**Comment by krlmlr** [comment]
Print file + line rather than context: https://github.com/hadley/testthat/issues/352

**Comment by krlmlr** [comment]
There are two possible file + line locations to report: The test that failed/warned/skipped, and the actual code that causes the error/warning/skip. The former should be always available, even if the latter is not (https://github.com/hadley/testthat/issues/352#issuecomment-175241596).

**Comment by hadley** [comment]
I think we should try for the actual line of code, and fall back to the test.

**Comment by krlmlr** [comment]
This is complete "as is", file + line information should be handled separately (#352).

**Pull request merged**
