### PR TITLE
New expect_output_file()

### PR DESCRIPTION
**Pull request by krlmlr**
Compares output against file contents, and optionally updates it.

With test, and using it already in this package.

I'm not really happy with the name, any suggestions?

### CODE REVIEW

**Comment by krlmlr** [comment]
I've been using this in some projects already, works for me (and for testthat). Any chance to include it in the upcoming point release, perhaps marked as "experimental"?

**Comment by hadley** [comment]
I think so - can you add a bullet to NEWS and I'll merge

**Comment by krlmlr** [comment]
Done, Travis test ok.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
