### PR TITLE
Add test coverage with coveralls.

### PR DESCRIPTION
**Pull request by jimhester**
I did not add this to the AppVeyor CI from https://github.com/hadley/testthat/pull/212 because I am not sure if Rtools will have `gcov` on windows.

### CODE REVIEW

**Comment by jimhester** [comment]
Ok it looks like 050ad78 is working properly.  If you enable the repo at https://coveralls.io/repos/new before you merge this pull it everything should be enabled.

**Comment by hadley** [comment]
Thanks!

**Comment by krlmlr** [comment]
@jimhester: [Rtools](https://github.com/krlmlr/r-portable/tree/master/Image/Rtools) appears to have`gcov`:

```
.../Rtools$ find -name "*gcov*"
./gcc-4.6.3/bin/gcov.exe
./gcc-4.6.3/lib/gcc/i686-w64-mingw32/4.6.3/64/libgcov.a
./gcc-4.6.3/lib/gcc/i686-w64-mingw32/4.6.3/libgcov.a
```

Coverage might be different on the two platforms, I'm not sure how coveralls would handle this.

**Comment by jimhester** [comment]
That is a decent point about the coverage being different on different platforms.

Thinking about this a little more coveralls has built in support for travis, with other CI systems you have to do more manual setup, so it wouldn't work with AppVeyor out of the box anyway.

Still might be something to look into in the future for `covr`, I'll open an issue to remind myself.

**Pull request merged**
