### PR TITLE
Report endless recursion

### PR DESCRIPTION
**Pull request by krlmlr**
Currently only contains a failing test.

Expected behavior: An error should be reported.

### CODE REVIEW

**Comment by krlmlr** [comment]
@hadley: The reason here is that handle_error() can't execute properly because the stack is already "almost full". 2d8429d399f2 demonstrates the principle by temporarily raising the limit, but I'll be looking for a better solution.

**Comment by krlmlr** [comment]
This now builds upon #494 and #495, and includes a better refactoring of the expectation code. Infinite recursions are now caught with a proper stack trace.

**Comment by krlmlr** [comment]
The output is way too large: 5b17d3ed0. Need to limit to first/last 20 entries?

**Comment by hadley** [comment]
@krlmlr I think keeping the first and last 10 would be great if >20 entries

**Comment by krlmlr** [comment]
Should be much better now. Setting options(expression = 200) for the output tests.

**Comment by hadley** [comment]
LGTM.

**Comment by krlmlr** [comment]
Thanks. Merging because it affects #470.

**Pull request merged**
