### PR TITLE
Remove old call-capturing code

### PR DESCRIPTION
**Pull request by krlmlr**
now handled in register_expectation().

### CODE REVIEW

**Comment by hadley** [comment]
I'm pretty sure that's still needed because of `signalCondition(e)`.  It's a bit ugly and confusing.

**Comment by krlmlr** [comment]
That depends if you want to rethrow the original error, or an updated version. I think this doesn't matter now. Who's going to look at the $call component of the rethrown error? In the original code, this was the tryCatch(error = ) handler; in the current code, there is an empty error handler.

**Comment by hadley** [comment]
Maybe for the default reporter so you get a more informative stacktrace for a bare test? I'm almost certain I put it there deliberately.

**Comment by krlmlr** [comment]
You're right -- reporter output gets distorted (and the tests don't catch it -- #379)...

**Pull request closed without merging**
