### PR TITLE
enable switching to the faster, time-stamp-based modification detection in auto_test() & auto_test_package()

### PR DESCRIPTION
**Pull request by katrinleinweber**
I haven't bench-marked the difference, just found it neat to have this option in the `auto_test()` functions, as well.

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Travis says: "LaTeX Error: File `xkeyval.sty' not found". Since there are several other errors in other PRs, I'm not sure whether mine triggered this or not.

**Comment by katrinleinweber** [comment]
Hello @krlmlr! There are currently no tests for the two functions I modified here. Would the recursion of testing `auto_test_package()` while testing `testthat` even be possible? 😉  Either way, I'm not sure how to fulfil the codecov target, sorry.

**Comment by krlmlr** [comment]
Thanks. I guess "user testing" is fine for this function.

Have you seen my [brushthat package](https://github.com/krlmlr/brushthat)? I'd be very much interested in auto_test() functionality there, too!

**Comment by katrinleinweber** [comment]
On my machine, `auto_test_package()` against `testthat [c7e83308](https://github.com/hadley/testthat/tree/c7e8330867645c174f9a286d00eb0036cea78b0c)` yields the same results as my modification `auto_test_package(hash = FALSE)`: some mismatches in the `reporters/..txt` files.

I also ran the following user test. Is that a valid approach in your view?

- [x] in my macOS: checking `/Library/Frameworks/R.framework/Versions/3.4/Resources/library` for the largest dir => `dplyr` (well, 10 MB)
- [x] in Terminal: `git clone https://github.com/tidyverse/dplyr.git --depth=1`
- [x] in RStudio: uninstalled `testthat` and reinstalled with `devtools::install_github("hadley/testthat")`
  - [x] in RStudio: associate new project with cloned `dplyr` folder & open
  - [x] `auto_test_package()` => some skipped, none failed
  - [x] back in `testthat` on my branch: Clean & Rebuild 
  - [x] back in `dplyr`: `auto_test_package(hash = FALSE)` => some skipped, **none failed**

This, together with the checks here seems to say: I regress nothing ;-D

I guess that to get more conclusive tests results, one would need to measure the reaction time of `watch(hash = TRUE)` vs. `watch(hash = FALSE)` in an even bigger package, but that is out-of-scope for me.

Please just consider this PR as enabling an existing, low-level option in the high-level functions as well.

**Comment by katrinleinweber** [comment]
Hello @krlmlr!

> […] "user testing" is fine for this function.

Does that mean the `codecov/patch` check can be ignored and this PR will be merged? Kind regards!

**Comment by hadley** [comment]
Thanks!

**Comment by katrinleinweber** [comment]
You're welcome :-)

**Pull request merged**
